[project]
name = "oodle"
version = "0.1.4"
description = "Oodle is a package that makes it easier to manage threads."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
license = "MIT"
authors = ["Zech Zimmerman <hi@zech.codes>"]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
